baseURL = 'https://lea-fish.github.io/'
languageCode = 'en-us'
title = 'Leafish'
defaultContentLanguage = 'en'

[params]
	description = "An open-source Minecraft client written in RUST"

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = -100
	
	[[menu.main]]
		identifier = "github"
		name = "GitHub"
		url = "https://github.com/Lea-fish/Leafish"

	
	[[menu.main]]
		identifier = "wiki"
		name = "Wiki"
		url = "https://github.com/Lea-fish/Leafish/wiki"

[languages]
	[languages.en]
		languageName = "English"
		weight = 1
	
	[languages.nl]
		languageName = "Nederlands"
		weight = 2
